version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -r backend/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 backend/manage.py test backend
      - store_artifacts:
          path: test-reports/
          destination: python_app